# Continous Integration setup for SU2.
# Tests with the SU2 develop branch when the TestCases repository is modified.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - padronas@stanford.edu
            - su2code-dev@lists.stanford.edu
        on_success: never
        on_failure: always
  
branches:
    only:
        - develop

env:
    global:
        CXXFLAGS=-O3
        BUILD_DIR=$TRAVIS_BUILD_DIR/SU2
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./configure --prefix=$BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        - CONFIGURE_COMMAND="./configure --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$BUILD_DIR"
          TEST_SCRIPT=parallel_regression.py

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2
    # Get the code
    - git clone https://github.com/su2code/SU2.git
    - cd SU2
    - git checkout develop

install:
    - echo $BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 4
    - make install
    
    # Add environmental variables according to the configure step
    - export SU2_RUN=$BUILD_DIR/bin
    - export SU2_HOME=$BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Go back to the test cases
    - cd ..

script:
    # run the tests
    python $TEST_SCRIPT

