# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

env:
    global:
        CXXFLAGS=-O3
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./configure --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        #- CONFIGURE_COMMAND="./configure --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR"
        #  TEST_SCRIPT=parallel_regression.py

install:
    - echo $TRAVIS_BUILD_DIR
    - echo pwd
    - echo ls







